export { Admin } from './Admin';
export { Detail } from './Detail';
export { Home } from './Home';
export { Login } from './Login';
export { Movies } from './Movies';
export { Series } from './Series';
export { SignUp } from './SignUP';
export { Users } from './Users';
export { Welcome } from './Welcome';
